### PR TITLE
Updated to work with Ansible 2.2

### PR DESCRIPTION
**Pull request by nwalke**
The current mongodb role is not compatible with Ansible 2.2.  I forked it and made it compatible.

### CODE REVIEW

**Comment by danvaida** [comment]
@nwalke what part is not compatible? have you seen https://github.com/lesmyrmidons/ansible-role-mongodb/issues/5#issuecomment-265119181 ?

**Comment by nwalke** [comment]
@danvaida I did, but I couldn't wait for that maintainer to come along and release it.  If you'd rather wait for them to do a new release, that's fine by me.

**Comment by danvaida** [comment]
nwalke the maintainer of that role has not tagged his current master branch, which I must say, is working as expected. although this is not in compliance with Ansible Galaxy, you can simply put 'master' as the version, and that will work just fine.

I do agree though, that we must make *some* change in this repo about this...

**Comment by nwalke** [comment]
The reason I don't want to do that is I'm installing this role from ansible-galaxy, not from Git, and we frequently reinstall roles. Any change I make will get blown away.  We do that to ensure that things are up to date and just to keep some sense of good ansible hygiene. 

Like I said, I understand if you don't want to incorporate this change.  Just thought I'd try to provide a solution.

**Comment by mariussturm** [comment]
Hi Nick,
thanks for the PR! Changing dependencies is nothing we do easily. There are always concerns like: Will this fork be maintained in the future? Can we trust the fork? Do we have to switch back at some point?... So I would prefer to work on the upstream repository to get this fixed. Given that the issue is not that old I think switching to another fork would not be what user expect from this role.
I can see that this would help in your environment but we have to make decissions for all users who use this role. So please keep on working with  lesmyrmidons role and try to get your fixes in there.
However I will add a note to the README that points out the incompatibilities with Ansible 2.2 and the issue with the MongoDB role.

Thanks!

**Comment by nwalke** [comment]
Understood.  Thanks!

**Pull request closed without merging**
