### PR TITLE
Add version to graylog tmp repository file

### PR DESCRIPTION
**Pull request by mlintern**
This would resolve https://github.com/Graylog2/graylog-ansible-role/issues/74

### CODE REVIEW

**Comment by mariussturm** [comment]
@mlintern thanks for the contribution, would you mind signing the CLA?

**Comment by juju2112** [comment]
Closing and reopening to force TravisCI to run new test suite.

**Comment by juju2112** [comment]
@mlintern I think the step that installs the package needs to be updated, as well. The tests fail because it's still referencing the old version of the filename.

```- name: "Graylog repository package should be installed"
  apt:
    deb: "/tmp/graylog_repository.deb"```

**Comment by juju2112** [comment]
Thanks, @mlintern!

**Pull request merged**
