### PR TITLE
Support (optional) server package version

### PR DESCRIPTION
**Pull request by veger**

### CODE REVIEW

**Comment by veger** [comment]
No idea why the test ended up red, there are not errors...?No idea why the test ended up red, there are not errors...?

**Comment by mariussturm** [comment]
Thanks for the PR!
There is a problem currently with the tests see https://github.com/Graylog2/graylog-ansible-role/issues/64
Is there a reason why you set the default version to 2.1 instead of the latest 2.2?

**Comment by veger** [comment]
Uhm... no, just the version we are currently using... :/ I can update if you want (although it is just the example)

**Comment by mariussturm** [comment]
Ok, I fix that later.

**Pull request merged**
