### PR TITLE
Change use of version_compare filter to version

### PR DESCRIPTION
**Pull request by kmonticolo**
The 'version_compare' filter was removed in 2.9 after being deprecated in 2.5.

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks again, please rebase the PR. The first commit was already fixed.

**Comment by LuPo** [comment]
Could you please rebase Kamil, otherwise I will create the new PR

**Comment by smutel** [comment]
Hello. I am using ansible 2.9 and very interesting by this MR.

**Comment by smutel** [comment]
Duplicate of #123

**Comment by juju2112** [comment]
Closing this as the changes are already commited to the main branch. I'll create a new tag as soon as I'm done updating the tests (https://github.com/Graylog2/graylog-ansible-role/pull/147).

**Pull request closed without merging**
