### PR TITLE
 fix set proxy settings as comment with a conditional check in the j2 …

### LINKED ISSUE #187: Proxy-Settings are written as comment into server.conf
Hi,
i just recognized that the proxy settings are written as a comment into the server.conf.

I think it helps to place a conditional check if the proxy variables are defined  and not empty.
I already adapted the Jinja2 template.

Cheers

### PR DESCRIPTION
**Pull request by xtruthx**
Add conditional to the Jinja2 template for server.conf to avoid that proxy settings are set as comment.
Closes #187

### CODE REVIEW

**Comment by xtruthx** [comment]
now it should be correct, sorry about the first wrong varname copy.

**Comment by mariussturm** [comment]
Hey,
thanks for the contribution! Looks good only the indentation is off. Could you please do it like it's done for the other conditions, e.g.: https://github.com/Graylog2/graylog-ansible-role/blob/bb94e9f224ccd64af634ae59c1959c9d06d78686/templates/graylog.server.conf.j2#L176

Thank you!

**Comment by xtruthx** [comment]
Thx @mariussturm i removed the identation.

**Comment by mariussturm** [comment]
Cool, thank you very much!

**Comment by xtruthx** [comment]
Your welcome, thx for the fast response.

**Pull request merged**
