### PR TITLE
Various mods

### PR DESCRIPTION
**Pull request by danvaida**
I will try to explain my commits.

Galaxy is about roles, so playbooks and inventories are not in that scope.

When there are such roles inter-dependencies and they're pulled automatically from Galaxy, in the idea of minimizing the amount of customizations / manual steps required to adapt the newly installed roles, variables precedence can be used. This also eliminates the extra confusion and makes the role compliant with Galaxy rules.

When used, ES writes in the log file that PermSize & MaxPermSize are deprecated since version 0.8.

Prefixing all role vars with the role name is part of the Galaxy standards.

On the todo list: list nginx as a dependency

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks for the PR, great work!
Couple of things here:
Our main goal is it to provide a solution for users to install Graylog as easy as possible. That was the main reason for us to provide an inventory and a playbook example. The goal should be that a user with little knowledge about Graylog and Ansible is able to deploy the application (plus dependencies) to a remote or local server. In the current state a user only needs to put the IP address of the server into the inventory file and run a single command.
With your changes a user needs to create those files, need to know the format... I can see that this goes more into the direction of advanced Ansible users who already have a bigger setup and want to integrate this role. So technically nothing wrong just for my understanding not as userfriendly as it could be. Maybe I am missing something? Or we have to improve the documentation then?

The same goes for the variable renames, technically good but in practise this means the user has multiple places for shared settings. E.g. the ES clustername needs to be set in `graylog_elasticsearch_cluster_name` and also in `elasticsearch_cluster_name`?
Do you see any way to improve here?

**Comment by craigglennie** [comment]
I think @danvaida has done a great job here. As it stands, this setup doesn't let you install graylog as a role via your own playbook - it breaks with missing variables, and I think it's down to having a playbook masquerading as a role. This is a problem if you're advertising the role in Ansible Galaxy, as people expect to be able to drop it into their playbook and have it work.

I spent a lot of time trying to debug this (still new to Ansible) and switching to @danvaida's branch fixed my issue. Now I can use graylog as a role in my own playbook. I understand the arguments about making things simpler for the user, so maybe there could be two versions - one for people who want a simple, standalone install (this one) and another version on Ansible Galaxy for users who want to drop Graylog in as a role in their own playbook.

**Comment by danvaida** [comment]
Couldn't have said it better myself :) Thanks for the explanation! And the
suggestion makes sense to me as well.
Cheers.

**Comment by mariussturm** [comment]
Thanks for the feedback guys! Would it be feasible to merge this PR and make this a clean Ansible role and then provide some kind of script that generate a playbook and inventory for first time users? In that way we could help people to get the dependencies right and advanced users could simply use the role. Or is this uncommon/not valid for a role?

**Comment by craigglennie** [comment]
How about just providing the instructions for creating a playbook to use the role? All you need to do to get this to work is:

- `ansible-galaxy install graylog2.graylog`
- Create a `playbook.yml` in the same directory, containing the following
```yaml
---
- hosts: all

  roles:
      - { role: graylog2.graylog, sudo: yes }
```
- Run it with `ansible-playbook playbook.yml -i "127.0.0.1,"` or create an inventory file (better) and use that.

If people using Ansible can't manage this they should probably be using the pre-built Graylog VMs instead.

**Comment by mariussturm** [comment]
Sounds good, let's try this.

**Pull request merged**
